#!/bin/sh
arg=$1

#----- TODO: Change ssm packages for remote runs

NAME="GenPhysX"
DESC="Geophysical field generator."
VERSION="2.0.1"
MAINTAINER="Jean-Philippe Gauthier"

SSM_NAME=${NAME}_${VERSION}_${ORDENV_PLAT}

MAKE=make
SPI_VERSION=7.6.2
TCL=/cnfs/ops/cmoe/afsr005/Lib/${SPI_VERSION}/${ORDENV_PLAT}/SPI
#TCL=/ssm/net/cmoe/apps/SPI_${SPI_VERSION}_all/lib/${ORDENV_PLAT}
LIB=/cnfs/ops/cmoe/afsr005/Lib/${SPI_VERSION}/${ORDENV_PLAT}

unset LD_LIBRARY_PATH

export CC=c99

echo ""
echo "----- Building platform : ${ORDENV_PLAT} -----"
echo ""

if [[ $arg = "ssm" ]]; then

   echo ""
   echo "----- Building ssm package : ${SSM_DEV}/workspace/${SSM_NAME} -----"
   echo ""
   rm -f -r ${SSM_DEV}/workspace/${SSM_NAME} ${SSM_DEV}/package/${SSM_NAME}.ssm 
   mkdir -p ${SSM_DEV}/workspace/${SSM_NAME}/.ssm.d ${SSM_DEV}/workspace/${SSM_NAME}/etc/profile.d
   cp -r ../bin ${SSM_DEV}/workspace/${SSM_NAME}
   cp -r ../lib ${SSM_DEV}/workspace/${SSM_NAME}
   cp -r ../tcl ${SSM_DEV}/workspace/${SSM_NAME}
   cp -r ../doc ${SSM_DEV}/workspace/${SSM_NAME}
   cp ../.ssm.d/post-install ${SSM_DEV}/workspace/${SSM_NAME}/.ssm.d
   find ${SSM_DEV}/workspace/${SSM_NAME} -name .svn -exec rm -f -r {} \;
   sed -e "s/NAME/${NAME}/" -e "s/VERSION/${VERSION}/" -e "s/PLATFORM/${ORDENV_PLAT}/" -e "s/MAINTAINER/${MAINTAINER}/" -e "s/DESC/${DESC}/" ../.ssm.d/control > ${SSM_DEV}/workspace/${SSM_NAME}/.ssm.d/control
   cd ${SSM_DEV}/workspace; tar -zcvf ${SSM_DEV}/package/${SSM_NAME}.ssm ${SSM_NAME}
else

echo ""
echo "----- Making TclGeoPhy Library Object -----"
echo ""
   if [[ $arg = "reconf" ]]; then
      make distclean
      ./configure \
         --exec-prefix=${TCL}/TclTk \
         --enable-threads \
         --enable-64bit \
         --with-tcl=${TCL}/TclTk/lib \
         --with-tk=${TCL}/TclTk/lib \
         --with-eer=/ssm/net/cmoe/eer/beta/${ORDENV_PLAT} \
         --with-rmn=${LIB}/librmn-14 \
         --with-gdal=${LIB}/gdal-1.10.0/bin/gdal-config
   fi

   $MAKE install
fi
