#!/bin/sh
arg=$1

#----- TODO: Change ssm packages for remote runs

NAME="GenPhysX"
DESCRIPTION="Geophysical field generator."
SUMMARY="Tool to generate geophysical fields (ME,MG,VG,...) for meteorological and environmental models (GEM,GEM-MACH,...)"
VERSION="2.5.2"
MAINTAINER="Vanh.Souvanlasy@canada.ca, Jean-Philippe.Gauthier@canada.ca"
BUILDINFO=`git describe --always`

if [[ -n $COMP_ARCH ]]; then
   COMP=-${COMP_ARCH}
fi

SSM_VERSION=${VERSION}${COMP}
SSM_NAME=${NAME}_${VERSION}${COMP}_${ORDENV_PLAT}

MAKE=make
SPI_VERSION=8.0.0
LIB_EER=${SSM_DEV}/workspace/eerUtils_3.4.0${COMP}_${ORDENV_PLAT}           #----- Location of eer library
LIB_PATH=${SSM_DEV}/workspace/libSPI_${SPI_VERSION}${COMP}_${ORDENV_PLAT}                              

export LD_LIBRARY_PATH=${LIB_PATH}/lib:$LD_LIBRARY_PATH
export LIBRARY_PATH=${LIB_PATH}/lib:$LIBRARY_PATH

if [[ -n $INTELCOMP_HOME ]]; then
   export CC=icc
   export CXX=icpc
fi

export CFLAGS="-std=c99 -Winline"
type -P autoconf2.50 && autoconf=autoconf2.50 || autoconf=autoconf

echo ""
echo "----- Building platform : ${ORDENV_PLAT} -----"
echo ""

if [[ $arg = "-ssm" ]]; then

   echo ""
   echo "----- Building ssm package : ${SSM_DEV}/workspace/${SSM_NAME} -----"
   echo ""
   rm -f -r ${SSM_DEV}/workspace/${SSM_NAME} ${SSM_DEV}/package/${SSM_NAME}.ssm 
   mkdir -p ${SSM_DEV}/workspace/${SSM_NAME}/.ssm.d ${SSM_DEV}/workspace/${SSM_NAME}/etc/profile.d
   cp -r ../bin ${SSM_DEV}/workspace/${SSM_NAME}
   cp -r ../lib ${SSM_DEV}/workspace/${SSM_NAME}
   cp -r ../tcl ${SSM_DEV}/workspace/${SSM_NAME}
   cp -r ../doc ${SSM_DEV}/workspace/${SSM_NAME}
   cp ../.ssm.d/post-install ${SSM_DEV}/workspace/${SSM_NAME}/.ssm.d
   find ${SSM_DEV}/workspace/${SSM_NAME} -name .svn -exec rm -f -r {} \;
   sed -e "s/NAME/${NAME}/" -e "s/VERSION/${SSM_VERSION}/" -e "s/PLATFORM/${ORDENV_PLAT}/" -e "s/MAINTAINER/${MAINTAINER}/" -e "s/BUILDINFO/${BUILDINFO}/" -e "s/DESCRIPTION/${DESCRIPTION}/" -e "s/SUMMARY/${SUMMARY}/" ../.ssm.d/control.json > ${SSM_DEV}/workspace/${SSM_NAME}/.ssm.d/control.json
   cd ${SSM_DEV}/workspace; tar -zcvf ${SSM_DEV}/package/${SSM_NAME}.ssm ${SSM_NAME}
   rm -f -r ${SSM_NAME}
else

echo ""
echo "----- Making TclGeoPhy Library -----"
echo ""
   if [[ $arg = "-reconf" ]]; then
      make distclean
      $autoconf
      ./configure \
         --exec-prefix=${LIB_PATH}/TCL \
         --enable-threads \
         --enable-64bit \
         --with-tcl=${LIB_PATH}/TCL/lib \
         --with-tk=${LIB_PATH}/TCL/lib \
         --with-eer=${LIB_EER} \
         --with-rmn=${LIB_EER} \
         --with-gdal=`which gdal-config`
   fi

   $MAKE install
fi
